### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ngtk** [ngtk/departure#3]
## Testing
- [x] RSpec
- [x] shoulda-matcher
- [x] capybara
- [x] timecop
- [x] FactoryGirl
# Debug
- [x] annotate
- [x] better_errors
- [x] binding_of_caller
- [x] hirb, hirb-unicord
- [x] pry
- [x] awesome print
- [x] quiet_assets
# Lint
- [x] scss_lint
- [x] rubocop
# Enhancement
- [x] spring
- [x] config
- [x] squeel
- [x] cancancan
- [x] papertrail
- [x] kaminari
- [x] default_value_for
- [x] delayed_job
- [x] draper
- [x] simple_form
- [x] aasm
- [x] devise
- [x] paperclip
